vim.keymap.set('n', '<C-k>', ':wincmd k<CR>', {})
vim.keymap.set('n', '<C-j>', ':wincmd j<CR>', {})
vim.keymap.set('n', '<C-h>', ':wincmd h<CR>', {})
vim.keymap.set('n', '<C-l>', ':wincmd l<CR>', {})
vim.keymap.set("n", "<C-h>", ":TmuxNavigateLeft<CR>", {})
vim.keymap.set("n", "<C-j>", ":TmuxNavigateDown<CR>", {})
vim.keymap.set("n", "<C-k>", ":TmuxNavigateUp<CR>", {})
vim.keymap.set("n", "<C-l>", ":TmuxNavigateRight<CR>", {})

vim.keymap.set("n", "<A-l>", ":BufferNext<CR>", {})
vim.keymap.set("n", "<A-h>", ":BufferPrevious<CR>", {})
vim.keymap.set("n", "<C-w>", ":BufferClose<CR>", {})
vim.keymap.set("n", "<C-T>", ":BufferRestore<CR>", {})

vim.keymap.set('i', 'jj', '<Esc>', {})
vim.keymap.set('i', '<C-s>', vim.lsp.buf.signature_help, {})
vim.keymap.set('n', '<S-Tab>', ':NvimTreeFocus<CR>', {})
vim.keymap.set('n', '<A-k>', ":m .-2<CR>==", { noremap = true, silent = true })
vim.keymap.set('n', '<A-j>', ":m .+<CR>==", { noremap = true, silent = true })
vim.keymap.set('i', '<A-k>', "<Esc>:m .-2<CR>==gi", { noremap = true, silent = true })
vim.keymap.set('i', '<A-j>', "<Esc>:m .+<CR>==gi", { noremap = true, silent = true })
vim.keymap.set('v', '<A-k>', ":m '<-2<CR>gv=gv", { noremap = true, silent = true })
vim.keymap.set('v', '<A-j>', ":m '>+<CR>gv=gv", { noremap = true, silent = true })

vim.keymap.set('n', '<leader>xx', ':Trouble diagnostics toggle<CR>', {})

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-p>', builtin.find_files, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = 'Telescope live grep' })
